name: Cypress Tests
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Cypress tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        # uses: bahmutov/npm-install@v1
        run: npm install
        
      - name: Build
        run: npm run build

      - uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Run Tests
        uses: cypress-io/github-action@v4
        with:
          start: npm run start
          wait-on: 'http://localhost:3000'
          browser: 'Replay Firefox'    
        env:
          RECORD_ALL_CONTENT: 1
          RECORD_REPLAY_METADATA_FILE: /tmp/replay-metadata
      - name: Upload
        uses: replayio/action-upload@v0.4.5
        with:
          api-key: rwk_uVKsV0CXSMo3OPQuwQVfk4T4LNzLKMQ7eQr9UKJgTPu
          public: false
